name: API CI

on:
  pull_request:
    paths:
      - "api/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x 
    - name: yarn install, build, and test
      run: |
        cd api
        yarn install
        yarn build
        yarn test
      env:
        CI: true