name: API CI

on:
  push:
    paths:
      - "./api/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn build
        yarn test
      env:
        CI: true